### ISSUE TITLE
Compilation fails under Ubuntu 18.04

### ISSUE THREAD

**Issue by johannes-riecken** [pwithnall/walbottle#2]
I cloned the repository at 7e924543568b0211c580033cf0a50e78179a9574 and ran `./autogen.sh` and `make`. While running make I get errors like 
`utilities/json-validate.c:107:12: error: ‘EXIT_INVALID_OPTIONS’ undeclared (first use in this function)`

I've attached the output of the two commands I ran.
[autogen.log](https://github.com/pwithnall/walbottle/files/3085354/autogen.log)
[make.log](https://github.com/pwithnall/walbottle/files/3085359/make.log)

**Comment by pwithnall** [comment]
Thanks a lot. Merged manually since the upstream is actually https://gitlab.com/walbottle/walbottle.
